server:
  port: 6933

spring:
  redis:
    database: 0
    host: 139.196.124.122
    port: 6379
    password: 1994
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.196.124.122:3306/mogu_cache?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: root
    password: 1994

logging:
  level:
    root: info
    com.mogu: debug