server:
  port: 1506

spring:
  application:
    name: oauth2-authorization-server
  datasource:
    url: jdbc:mysql://localhost:3306/scn_oauth2?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1994
  redis:
    host: localhost
    port: 6379
    database: 7
