server:
  port: 1121

spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: SCN
        namespace: 4ee7ef32-c1ff-41bf-8e12-c05eea6f4f78

feign:
  hystrix:
    enabled: true
